### ISSUE TITLE
element 使用 () => import(xxx) 的形式引入组件，会导致切换路由时页面闪白屏

### ISSUE THREAD

**Issue by imsfc** [justbecoder/react-router-middleware-plus#3]
使用 createElement(lazy(() => import(xxx))) 则正常

**Comment by imsfc** [comment]
另外，useMiddlewareRoutes 和 useRoutes 第二个参数竟然不兼容的？

**Comment by imsfc** [comment]
哦，补充一下，是嵌套路由，外层是 Layout，但是切换子页面 Layout 也会白屏

**Comment by justbecoder** [comment]
你的路由中间件是怎么定义的，有demo吗

**Comment by imsfc** [comment]
[Demo](https://stackblitz.com/edit/vitejs-vite-bqobuz?file=src/layouts/Layout.tsx)
红色区域是Layout，但是切换页面红色区域会白屏一下
当时使用的是1.2.0版本

**Comment by justbecoder** [comment]
> 另外，useMiddlewareRoutes 和 useRoutes 第二个参数竟然不兼容的？

第二个参数给丢了，重新发布了最新版本1.4.0，和useRoutes参数一样

**Comment by smithyj** [comment]
@fx100 @justbecoder 已经PR解决闪屏问题，等代码合并下，#5

**Comment by justbecoder** [comment]
> @fx100 @justbecoder 已经PR解决闪屏问题，等代码合并下，#5

最新版本1.4.1已经发布，敬请使用
